<?xml version="1.0"?>

<robot name="suturo_door" xmlns:xacro="http://ros.org/wiki/xacro">

  
      <gazebo>
   <gravity>0</gravity>
</gazebo>

  <material name="door_green">
    <color rgba="0 0.31 0.22 1"/>
  </material>

  <material name="hinge_red">
    <color rgba="0.74 0.25 0.25 1"/>
  </material>

  <material name="handle_blue">
    <color rgba="0.3 0.5 0.78 1"/>
  </material>
  <xacro:property name="half_pi" value="1.570796327" /> 

  <xacro:macro name="suturo_door" params="name parent height width depth x y z zrot door_turn_limit_lower door_turn_limit_max handle_x handle_z">
    <!-- LINKS -->
    <!-- TODO: Remove gravity for door -->
    
    <link name="${name}:door_center">
      <visual>
        <material name="door_green"/>
        <origin xyz="${width/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${depth} ${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${width/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${depth} ${height}" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>
      

    <link name="${name}:door_hinge">
      <visual>
        <material name="hinge_red"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 ${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 ${height}" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
            <gazebo>
   <turnGravityOff>true</turnGravityOff>
</gazebo>
    </link>
	
	<link name="${name}:door_handle_link">
      <visual >
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry name="handle_blue">
          <cylinder radius="0.013" length="0.10" />
        </geometry>
      </visual>
      <collision >
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry name="handle_collision_geom">
          <cylinder radius="0.013" length="0.10" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
                  <gazebo>
   <turnGravityOff>true</turnGravityOff>
</gazebo>
    </link>

    <link name="${name}:door_handle_outside">

      <sphere_inertia radius="0" mass="0"/>
      <visual>
	<material name="handle_blue"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.015 0.15 0.01" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.015 0.15 0.01" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
                        <gazebo>
   <turnGravityOff>true</turnGravityOff>
</gazebo>
    </link>

    <link name="${name}:door_handle_inside">

      <sphere_inertia radius="0" mass="0"/>
      <visual>
	<material name="handle_blue"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.015 0.15 0.01" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.015 0.15 0.01" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>                        
      <gazebo>
   <turnGravityOff>true</turnGravityOff>
</gazebo>
    </link>
    
      
    
    <!-- JOINTS -->

    <joint name="${name}:door_origin_revolute_joint" type="revolute">
      <axis xyz="0 0 1"/>
      <limit effort="100" lower="${door_turn_limit_lower}" upper="${door_turn_limit_max}" velocity="10"/>
      <origin xyz="0 0 0" rpy="0 0 ${zrot}" />
      <parent link="${name}:door_hinge"/>
      <child link="${name}:door_center"/>
    </joint>

    <joint name="${name}:door_hinge_joint" type="fixed">
      <axis xyz="0 0 0"/>
      <limit effort="1" lower="0" upper="1.5708" velocity="1"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="${name}:door_hinge"/>
    </joint>

    <joint name="${name}:door_handle_joint" type="revolute" >
      <axis xyz="0 0 1"/>
      <limit effort="1" lower="0" upper="${pi/5}" velocity="1"/>
      <origin xyz="${handle_x} 0 ${handle_z}" rpy="${pi/2} 0 0" />
      <parent link="${name}:door_center"/>
	  <child link="${name}:door_handle_link"/>
    </joint>

    <joint name="${name}:door_handle_inside_joint" type="fixed">
      <origin xyz="-0.04 0 0.06" rpy="0 0 ${pi/2}" />
      <parent link="${name}:door_handle_link"/>
      <child link="${name}:door_handle_inside"/>
    </joint>
	
    <joint name="${name}:door_handle_outside_joint" type="fixed">
      <origin xyz="-0.075 0 -0.05" rpy="0 0 ${-pi/2}" />
      <parent link="${name}:door_handle_link"/>
      <child link="${name}:door_handle_outside"/>
    </joint>

  </xacro:macro>
</robot>
