<?xml version="1.0"?>

<robot name="suturo_wall" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="wall_pink">
    <color rgba="0.95 0.43 0.96 1"/>
  </material>

  <xacro:macro name="suturo_wall" params="name parent pos_1_x pos_1_y pos_2_x pos_2_y">

    <xacro:property name="center_x" value="${ (pos_1_x + pos_2_x) / 2}"/>
    <xacro:property name="center_y" value="${ (pos_1_y + pos_2_y) / 2}"/>

    <xacro:property name="dist_x" value="${sqrt((pos_1_x - pos_2_x ) ** 2)}"/>
    <xacro:property name="dist_y" value="${sqrt((pos_1_y - pos_2_y ) ** 2)}"/>



    <xacro:property name="length" value="${sqrt( ((dist_x **2)  + (dist_y **2)) )}"/>
    <xacro:property name="z_rotation" value="${acos( dist_x / length)}"/>

    <joint name="${name}_center_joint" type="fixed">
      <origin xyz="${center_x} ${center_y} 0.3"/>
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <visual>
        <material name="wall_pink"/>
        <origin xyz="0 0 0" rpy="0 0 ${z_rotation}"/>
        <geometry>
          <box size="${length} 0.06 0.6" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${z_rotation}"/>
        <geometry>
          <box size="${length} 0.06 0.6" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>

  </xacro:macro>

</robot>
