<?xml version="1.0"?>

<robot name="suturo_shelf" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="shelf_blue">
    <color rgba="0.59 0.88 0.9 1"/>
  </material>
  <material name="shelf_door_green">
    <color rgba="0.64 0.87 0.82 1"/>
  </material>


  <xacro:macro name="suturo_shelf" params="name parent *origin size_x size_y size_z floors_height number_of_floors door">
    
    <!-- General conveinience links -->
    <link name="${name}_shelf_origin"/>
    <link name="${name}_shelf_center"/>
    <link name="${name}_shelf_base_center"/>

    <joint name="${name}_shelf_origin_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_shelf_origin"/>
    </joint>

    <joint name="${name}_shelf_center_joint" type="fixed">
      <origin xyz="${size_x/2} ${size_y/2} ${size_z/2}" rpy="0 0 0" />
      <parent link="${name}_shelf_origin"/>
      <child link="${name}_shelf_center"/>
    </joint> 

    <joint name="${name}_shelf_base_center_joint" type="fixed">
      <origin xyz="${size_x/2} ${size_y/2} 0.0" rpy="0 0 0" />
      <parent link="${name}_shelf_origin"/>
      <child link="${name}_shelf_base_center"/>
    </joint> 


    <!-- WALLS -->
    <xacro:suturo_shelf_piece name="${name}_shelf_back" parent="${name}_shelf_origin"
      size_x="0.01" size_y="${size_y}" size_z="${size_z}">
      <origin xyz="${size_x} ${size_y/2} ${size_z/2}" rpy="0 0 0"/>
    </xacro:suturo_shelf_piece>

    <xacro:suturo_shelf_piece name="${name}_shelf_right_side" parent="${name}_shelf_origin"
      size_x="${size_x}" size_y="0.01" size_z="${size_z}">
      <origin xyz="${size_x/2} 0.0 ${size_z/2}" rpy="0 0 0"/>
    </xacro:suturo_shelf_piece>

    <xacro:suturo_shelf_piece name="${name}_shelf_left_side" parent="${name}_shelf_origin"
      size_x="${size_x}" size_y="0.01" size_z="${size_z}">
      <origin xyz="${size_x/2} ${size_y} ${size_z/2}" rpy="0 0 0"/>
    </xacro:suturo_shelf_piece>



    <xacro:macro name="shelf_floor_loop" params="floor_number">
        <xacro:suturo_shelf_piece name="${name}_shelf_floor_${floor_number}" parent="${name}_shelf_base_center"
          size_x="${size_x}" size_y="${size_y}" size_z="0.04" box_z_offset="-0.02">
        <origin xyz="0.0 0.0 ${floors_height[floor_number]}" rpy="0 0 0"/>
      </xacro:suturo_shelf_piece>
      <xacro:if value="${(number_of_floors - 1) > floor_number}">
            <xacro:shelf_floor_loop floor_number="${floor_number + 1}" />
      </xacro:if>
    </xacro:macro>

    <xacro:shelf_floor_loop floor_number="0" />


    <!-- ****************SHELF DOOR**************** -->
    <!-- left -->
    <xacro:if value="${door == 'left'}">
      <xacro:suturo_shelf_left_door name="${name}_shelf_door_left" parent="${name}_left_side"
        size_x="0.01" size_y="${size_y/2}" size_z="${size_z}" shelf_x_size="${size_x}">
        <origin xyz="0 ${size_y*0.75} ${size_z/2}" rpy="0 0 0"/>
      </xacro:suturo_shelf_left_door>
    </xacro:if>

    <!-- right -->
    <xacro:if value="${door == 'right'}">
      <xacro:suturo_shelf_right_door name="${name}_shelf_door_right" parent="${name}_right_side"
        size_x="0.01" size_y="${size_y/2}" size_z="${size_z}" shelf_x_size="${size_x}">
        <origin xyz="0 ${size_y*0.75} ${size_z/2}" rpy="0 0 0"/>
      </xacro:suturo_shelf_right_door>
    </xacro:if>

    <!-- both -->
    <xacro:if value="${door == 'both'}">
      <xacro:suturo_shelf_left_door name="${name}_shelf_door_left" parent="${name}_left_side"
        size_x="0.01" size_y="${size_y/2}" size_z="${size_z}" shelf_x_size="${size_x}">
        <origin xyz="0 ${size_y*0.75} ${size_z/2}" rpy="0 0 0"/>
      </xacro:suturo_shelf_left_door>

      <xacro:suturo_shelf_right_door name="${name}_shelf_door_right" parent="${name}_shelf_right_side"
        size_x="0.01" size_y="${size_y/2}" size_z="${size_z}" shelf_x_size="${size_x}">
        <origin xyz="0 ${size_y*0.75} ${size_z/2}" rpy="0 0 0"/>
      </xacro:suturo_shelf_right_door>
    </xacro:if>

  </xacro:macro>




  <!-- Creates a link with collision and visual box of given dimensions,
  and a respective joint to append it to the parent with given origin.  -->
  <xacro:macro name="suturo_shelf_piece" params="name parent *origin box_z_offset=0.0 size_x size_y size_z">

    <!-- LINK -->
    <link name="${name}">
      <visual>
        <material name="shelf_blue"/>
        <origin xyz="0 0 ${box_z_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${box_z_offset}" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </collision>
    </link>

    <!-- JOINT -->
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>
  </xacro:macro>


  <xacro:macro name="suturo_shelf_left_door" params="name parent *origin size_x size_y size_z shelf_x_size">

    <link name="${name}_link">
      <visual>
        <material name="shelf_door_green"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_shelf_joint" type="revolute">
      <origin xyz="${shelf_x_size/-2} ${size_y/-2} 0" rpy="0 0 3.1416"/>
      <axis xyz="0 0 1" />
      <parent link="${parent}_piece"/>
      <child link="${name}_link"/>
      <limit effort="30" velocity="1.0" lower="0.0" upper="1.91986" />
    </joint>
  </xacro:macro>


  <xacro:macro name="suturo_shelf_right_door" params="name parent *origin size_x size_y size_z shelf_x_size">

    <link name="${name}_shelf_link">
      <visual>
        <material name="shelf_door_green"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_shelf_joint" type="revolute">
      <origin xyz="${shelf_x_size/-2} ${size_y/2} 0" rpy="0 0 -3.1416"/>
      <axis xyz="0 0 1" />
      <parent link="${parent}_shelf_piece"/>
      <child link="${name}_shelf_link"/>
      <limit effort="30" velocity="1.0" lower="0.0" upper="1.91986" />
    </joint>
  </xacro:macro>


</robot>
