<?xml version="1.0"?>

<robot name="suturo_table" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="table_grey">
    <color rgba="0.8 0.8 0.8 1"/>
  </material>

  <xacro:macro name="suturo_table" params="name parent *origin size_x size_y size_z">
    <!-- LINKS -->

    <link name="${name}:table_center">
      <visual>
        <material name="table_grey"/>
        <origin xyz="0 0 ${-(size_z)/2}" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${-(size_z)/2}" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </collision>
    </link> 
    

    <link name="${name}:table_origin"/>
    
    <link name="${name}:table_front_edge_center"/>
    
    <!-- JOINTS -->

    <joint name="${name}:table_origin_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}:table_origin"/>
    </joint>

    <joint name="${name}:center_joint" type="fixed">
      <origin xyz="${size_x/2} ${size_y/2} ${size_z}" rpy="0 0 0" />
      <parent link="${name}:table_origin"/>
      <child link="${name}:table_center"/>
    </joint>
    
    <joint name="${name}:table_front_edge_center_joint" type="fixed">
      <origin xyz="0 ${size_y/2} ${size_z}" rpy="0 0 0" />
      <parent link="${name}:table_origin"/>
      <child link="${name}:table_front_edge_center"/>
    </joint> 
  </xacro:macro>
</robot>
