<?xml version="1.0"?>

<robot name="suturo_door" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="door_green">
    <color rgba="0 0.31 0.22 1"/>
  </material>

  <material name="hinge_red">
    <color rgba="0.74 0.25 0.25 1"/>
  </material>

  <material name="handle_blue">
    <color rgba="0.3 0.5 0.78 1"/>
  </material>
  <xacro:property name="half_pi" value="1.570796327" /> 

  <xacro:macro name="suturo_door" params="name parent height width depth x y z zrot door_turn_limit_lower door_turn_limit_max">
    <!-- LINKS -->


    <link name="${name}_door_center">
      <visual>
        <material name="door_green"/>
        <origin xyz="${width/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${depth} ${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${width/2} 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${width} ${depth} ${height}" />
        </geometry>
      </collision>
    </link>
      

    <link name="${name}_door_hinge">
      <visual>
        <material name="hinge_red"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 ${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>-
          <box size="0.05 0.05 ${height}" />
        </geometry>
      </collision>
    </link>

    <link name="${name}_door_handle_outside">

      <sphere_inertia radius="0" mass="0"/>
      <visual>
	<material name="handle_blue"/>
        <origin xyz="0 0 0" rpy="${half_pi} 0 ${pi}" />
        <geometry>-
          <box size="0.15 0.03 0.03" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${half_pi} 0 ${pi}" />
        <geometry>
          <box size="0.15 0.03 0.03" />
        </geometry>
      </collision>
    </link>

    <link name="${name}_door_handle_inside">

      <sphere_inertia radius="0" mass="0"/>
      <visual>
	<material name="handle_blue"/>
        <origin xyz="0 0 0" rpy="${half_pi} 0 ${pi}" />
        <geometry>-
          <box size="0.15 0.03 0.03" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${half_pi} 0 ${pi}" />
        <geometry>
          <box size="0.15 0.03 0.03" />
        </geometry>
      </collision>
    </link>
    
      
    
    <!-- JOINTS -->

    <joint name="${name}_door_origin_revolute_joint" type="revolute">
      <axis xyz="0 0 1"/>
      <limit effort="100" lower="${door_turn_limit_lower}" upper="${door_turn_limit_max}" velocity="10"/>
      <origin xyz="0 0 0" rpy="0 0 ${zrot}" />
      <parent link="${name}_door_hinge"/>
      <child link="${name}_door_center"/>
    </joint>

    <joint name="${name}_door_hinge_joint" type="fixed">
      <axis xyz="0 0 0"/>
      <limit effort="1" lower="0" upper="1.5708" velocity="1"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="${name}_door_hinge"/>
    </joint>

    <joint name="${name}_door_handle_inside_joint" type="fixed">
      <axis xyz="0 0 0"/>
      <limit effort="1" lower="0" upper="1.5708" velocity="1"/>
      <origin xyz="${0.9 * width} ${-depth} -0.1" rpy="0 0 0" />
      <parent link="${name}_door_center"/>
      <child link="${name}_door_handle_inside"/>
    </joint>
	
    <joint name="${name}_door_handle_outside_joint" type="fixed">
      <axis xyz="0 0 0"/>
      <limit effort="1" lower="0" upper="1.5708" velocity="1"/>
      <origin xyz="${0.9 * width} ${depth} -0.1" rpy="0 0 0" />
      <parent link="${name}_door_center"/>
      <child link="${name}_door_handle_outside"/>
    </joint>

  </xacro:macro>
</robot>
