name: 'Catkin Build SUTURO_RESOURCES'

on:
  push:
    branches: [ ci_test ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker and Build SUTURO Resources
      run: docker pull ros:melodic-ros-core && mkdir resources && wget -q -O entrypoint.sh https://raw.githubusercontent.com/SUTURO/suturo_ci/master/entrypoints/build_suturo_resources.sh && cp * resources && wget -q -O Dockerfile https://raw.githubusercontent.com/SUTURO/suturo_ci/master/Dockerfiles/ResourcesDockerfile && docker build . --file Dockerfile --no-cache=True --tag my-image-name:$(date +%s)
